---
title: "4_RObjects"
author: "sanudelhi1199"
date: "5/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# introducing R objects 

# vectors 
## hold values of same class and declared using vector () and c()

```{r vector}

v1 <- c(1,2,3,4,5,6,7,8,9,10)

v1


class(v1)

v2 <- c("hitesh","gajuji","solanki")

v2

class(v2)

v3 <- c(T,F)

v3

class(v3)

### how to create vactor using vactor ()

v4 <- vector("numeric", length = 20)

v4 

class(v4)

length(v4)

### concatinating vector meaning mixing two vector of diffrent class and auto assigning mutual class

v5 <- c("hitesh" , "gajuji")

v6 <- c(1,2)

v7 <- c(v5,v6)

v7 

class(v7)

v8 <- c(T,F)

class(v8)

v9 <- c("True", "False")

class(v9)

v10 <- c(v8,v9)

v10

class(v10)


### how to print ABCD

v11 <- letters[1:26]

v11


### how to do external cohersion using as.xxx() function

v12 <- 1:10

v12

class(v12)

v13 <-as.numeric(v12)

class(v13)

v14 <- as.character(v12)

class(v14)

v15 <- as.logical(v12)

v15

class(v15)



v16 <- "hitesh"

v17 <- as.numeric(v16)

class(v17)

v17


### how to get attributes 


v18 <- "my name is hitesh"

attributes(v18)


```




# list ()
## can hold value of multiple class


```{r list}
### while creating list each item is seperate vector

l1 <- list("hitesh", 5 , T)

l1

class(l1)

attributes(l1)

### how to assign names to list objects 

l2 <- list("names" = c("hitesh","gajuji"), "Age" = c(22,50), "alive"= c(T,T))

l2

class(l2)

attributes(l2)


### hoe to check if it is list

class(l2)

is.list(l2)

### how to give name to list after creating list


l3 <- list(c("hitesh","gajuji"),c(22,50), c(T,T))

l3

names(l3) <- c("name","age","alive")


l3

### how to get value from list

l3

l3[[1]]

l3[[2]]

l3[[3]]

l3

### how to get well output using str

l4 <-str(l3)
l4

### how to get specific output from list

l3[[1]]

l3$name[[1]]

l3$name[[2]]

# using similar function 


l4 <- list("name" = "rashmika", "age" = 30, "alive" = T)

l2 <- list("names" = c("hitesh","gajuji"), "Age" = c(22,50), "alive"= c(T,T), similar = l4)

l2

# getting perticulat object from list


l2[[1]]

l2$names[[1]]

l2$similar[[1]]

l2$similar$name[[1]]

### accessing a list item from name

l2$names

l2[["names"]]

l2[["Age"]]

### how to use logics to get list

l2


l2[c(T,F,T,F,T,F)]


### how to add vector in list


l2

vect <- "kamkhya"

vect2 <- 3

vect3 <- T

l2 <- list("names" = c("hitesh","gajuji", vect), "Age" = c(22,50, vect2), "alive"= c(T,T,vect3), similar = l4)


l2

```

